# Site settings
title: Ork me
email: vincent@ork.me
description: 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ork.me" # the base hostname & protocol for your site
twitter_username: toubiblag
github_username: Toubib

# Build settings
markdown: kramdown

permalink: /:title/

defaults:
  -
    scope:
      path: _posts/en
    values:
      layout: default
      lang: en
  -
    scope:
      path: _drafts/en
    values:
      layout: default
      lang: en
  -
    scope:
      path: _posts/fr
    values:
      layout: default
      lang: fr

gems:
  - jekyll-gist
